// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    introSidebar: ['intro'],
    onboardingSidebar: [{type: 'autogenerated', dirName: 'onboarding'}],
};

module.exports = sidebars;
