// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    introSidebar: ['intro'],
    onboardingSidebar: [{ type: 'autogenerated', dirName: 'onboarding' }],
    xatuSidebar: [{ type: 'autogenerated', dirName: 'xatu' }],
    interopSidebar: [{ type: 'autogenerated', dirName: 'interop' }],
};

module.exports = sidebars;
